In [1]:
import pandas as pd
import datetime
from datetime import time
import matplotlib.pyplot as plt

In [2]:
#2022. GODINA:

In [3]:
#UCITAVANJE PODATAKA
nez_opendata_2022 = pd.read_excel("nez-opendata-2022.xlsx")

In [4]:
#PRIKAZ TABELE
df_nez_opendata_2022 = pd.DataFrame(nez_opendata_2022)
df_nez_opendata_2022
df = df_nez_opendata_2022
df

,ID,Policijska uprava,Opština,Datum i vreme,Geolokacija(X),Geolokacija(Y),Vrsta,Tip,Opis
0,1351594,BEOGRAD,BARAJEVO,"01.01.2022,16:10",20.346290,44.603980,Sa povredjenim,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...
1,1351831,BEOGRAD,BARAJEVO,"01.01.2022,02:30",20.430508,44.580407,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak ulevo sa k...
2,1351921,BEOGRAD,BARAJEVO,"06.01.2022,11:00",20.398820,44.602510,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...
3,1352861,BEOGRAD,BARAJEVO,"06.01.2022,12:10",20.414231,44.577657,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...
4,1351871,BEOGRAD,BARAJEVO,"08.01.2022,20:15",20.344523,44.602351,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa leve strane kol...
...,...,...,...,...,...,...,...,...,...
15991,1377017,ŠABAC,ŠABAC,"28.06.2022,10:50",19.737673,44.715512,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgode sa učešćem jednog vozila i životinja
15992,1377934,ŠABAC,ŠABAC,"29.06.2022,21:00",19.741170,44.692048,Sa povredjenim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom bez prepreka na kolo...
15993,1377106,ŠABAC,ŠABAC,"29.06.2022,00:20",19.687943,44.837582,Sa povredjenim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...
15994,1377341,ŠABAC,ŠABAC,"29.06.2022,20:50",19.682128,44.745419,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Ostali sudari sa parkiranim vozilom
15995,1377477,ŠABAC,ŠABAC,"30.06.2022,12:15",19.702106,44.749145,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...

In [5]:
#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI
print("Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu je:")
count_ukupan_broj_u_srbiji = len(df)
print(count_ukupan_broj_u_srbiji)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU
print("Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu je:")
count_ukupan_broj_u_ns = len(df[df["Opština"]=="NOVI SAD"])
print(count_ukupan_broj_u_ns)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA SMRTNIM ISHODOM
print("Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_poginulim = len(df[df["Vrsta"]=="Sa poginulim"])
print(count_ukupan_broj_u_srbiji_sa_poginulim)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA SMRTNIM ISHODOM
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_poginulim = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa poginulim')])
print(count_ukupan_broj_u_ns_sa_poginulim) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA POVREDAMA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa povredama za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_povredama = len(df[df["Vrsta"]=="Sa povredjenim"])
print(count_ukupan_broj_u_srbiji_sa_povredama)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA POVREDAMA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_povredama = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa povredjenim')])
print(count_ukupan_broj_u_ns_sa_povredama) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA MATERIJALNOM STETOM
print("Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_mat_stetom = len(df[df["Vrsta"]=="Sa mat.stetom"])
print(count_ukupan_broj_u_srbiji_sa_mat_stetom)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA MATERIJALNOM STETOM
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_mat_stetom = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa mat.stetom')])
print(count_ukupan_broj_u_ns_sa_mat_stetom)

Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu je:
15996
Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu je:
1083
Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom za 2022. godinu je:
218
Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom za 2022. godinu je:
4
Ukupan broj saobracajnih nezgoda u Srbiji sa povredama za 2022. godinu je:
5918
Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama za 2022. godinu je:
483
Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom za 2022. godinu je:
9860
Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom za 2022. godinu je:
596

In [6]:
#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA PESACIMA
print("Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu sa pesacima je:")
count_ukupan_broj_u_srbiji_sa_pesacima = len(df[df['Tip']=="SN SA PEŠACIMA"])
print(count_ukupan_broj_u_srbiji_sa_pesacima)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA PESACIMA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu sa pesacima je:")
count_ukupan_broj_u_ns_sa_pesacima = len(df[(df["Opština"]=="NOVI SAD") & (df['Tip']=="SN SA PEŠACIMA")])
print(count_ukupan_broj_u_ns_sa_pesacima)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA SMRTNIM ISHODOM SA PESACIMA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom i pesacima za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_pesacima_sa_poginulim = len(df[(df["Vrsta"]=="Sa poginulim") & (df['Tip']=='SN SA PEŠACIMA')])
print(count_ukupan_broj_u_srbiji_sa_pesacima_sa_poginulim)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA SMRTNIM ISHODOM SA PESACIMA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom i pesacima za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_pesacima_sa_poginulim = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa poginulim') & (df['Tip']=='SN SA PEŠACIMA')])
print(count_ukupan_broj_u_ns_sa_pesacima_sa_poginulim) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA POVREDAMA I PESACIMA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa povredama i pesacima za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_pesacima_sa_povredama = len(df[(df["Vrsta"]=="Sa povredjenim") & (df['Tip']=='SN SA PEŠACIMA')])
print(count_ukupan_broj_u_srbiji_sa_pesacima_sa_povredama)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA POVREDAMA I PESACIMA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama i pesacima za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_pesacima_sa_povredama = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa povredjenim') & (df['Tip']=='SN SA PEŠACIMA')])
print(count_ukupan_broj_u_ns_sa_pesacima_sa_povredama) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA MATERIJALNOM STETOM I PESACIMA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom i pesacima za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_pesacima_sa_mat_stetom = len(df[(df["Vrsta"]=="Sa mat.stetom") & (df['Tip']=='SN SA PEŠACIMA')])
print(count_ukupan_broj_u_srbiji_sa_pesacima_sa_mat_stetom)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA MATERIJALNOM STETOM I PESACIMA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom i pesacima za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_pesacima_sa_mat_stetom = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa mat.stetom') & (df['Tip']=='SN SA PEŠACIMA')])
print(count_ukupan_broj_u_ns_sa_pesacima_sa_mat_stetom)

Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu sa pesacima je:
1168
Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu sa pesacima je:
83
Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom i pesacima za 2022. godinu je:
58
Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom i pesacima za 2022. godinu je:
1
Ukupan broj saobracajnih nezgoda u Srbiji sa povredama i pesacima za 2022. godinu je:
1092
Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama i pesacima za 2022. godinu je:
79
Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom i pesacima za 2022. godinu je:
18
Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom i pesacima za 2022. godinu je:
3

In [7]:
#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA PARKIRANIM VOZILIMA
print("Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu sa parkiranim vozilima je:")
count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom = len(df[df['Tip']=="SN SA PARKIRANIM VOZILIMA"])
print(count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA PARKIRANIM VOZILIMA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu sa parkiranim vozilima je:")
count_ukupan_broj_u_ns_sa_parkiranim_vozilom = len(df[(df["Opština"]=="NOVI SAD") & (df['Tip']=="SN SA PARKIRANIM VOZILIMA")])
print(count_ukupan_broj_u_ns_sa_parkiranim_vozilom)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA SMRTNIM ISHODOM SA PARKIRANIM VOZILIMA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom i parkiranim vozilima za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom_sa_poginulim = len(df[(df["Vrsta"]=="Sa poginulim") & (df['Tip']=='SN SA PARKIRANIM VOZILIMA')])
print(count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom_sa_poginulim)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA SMRTNIM ISHODOM SA PARKIRANIM VOZILIMA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom i parkiranim vozilima za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_parkiranim_vozilom_sa_poginulim = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa poginulim') & (df['Tip']=='SN SA PARKIRANIM VOZILIMA')])
print(count_ukupan_broj_u_ns_sa_parkiranim_vozilom_sa_poginulim) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA POVREDAMA I PARKIRANIM VOZILIMA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa povredama i parkiranim vozilima za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom_sa_povredama = len(df[(df["Vrsta"]=="Sa povredjenim") & (df['Tip']=='SN SA PARKIRANIM VOZILIMA')])
print(count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom_sa_povredama)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA POVREDAMA I PARKIRANIM VOZILIMA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama i parkiranim vozilima za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_parkiranim_vozilom_sa_povredama = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa povredjenim') & (df['Tip']=='SN SA PARKIRANIM VOZILIMA')])
print(count_ukupan_broj_u_ns_sa_parkiranim_vozilom_sa_povredama) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA MATERIJALNOM STETOM I PARKIRANIM VOZILIMA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom i parkiranim vozilima za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom_sa_mat_stetom = len(df[(df["Vrsta"]=="Sa mat.stetom") & (df['Tip']=='SN SA PARKIRANIM VOZILIMA')])
print(count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom_sa_mat_stetom)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA MATERIJALNOM STETOM I PARKIRANIM VOZILIMA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom i parkiranim vozilima za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_parkiranim_vozilom_sa_mat_stetom = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa mat.stetom') & (df['Tip']=='SN SA PARKIRANIM VOZILIMA')])
print(count_ukupan_broj_u_ns_sa_parkiranim_vozilom_sa_mat_stetom)

Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu sa parkiranim vozilima je:
2487
Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu sa parkiranim vozilima je:
166
Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom i parkiranim vozilima za 2022. godinu je:
9
Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom i parkiranim vozilima za 2022. godinu je:
0
Ukupan broj saobracajnih nezgoda u Srbiji sa povredama i parkiranim vozilima za 2022. godinu je:
170
Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama i parkiranim vozilima za 2022. godinu je:
11
Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom i parkiranim vozilima za 2022. godinu je:
2308
Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom i parkiranim vozilima za 2022. godinu je:
155

In [8]:
#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA JEDNIM VOZILOM
print("Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu sa jednim vozilom je:")
count_ukupan_broj_u_srbiji_sa_jednim_vozilom = len(df[df['Tip']=="SN SA JEDNIM VOZILOM"])
print(count_ukupan_broj_u_srbiji_sa_jednim_vozilom)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA JEDNIM VOZILOM
print("Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu sa jednim vozilom je:")
count_ukupan_broj_u_ns_sa_jednim_vozilom = len(df[(df["Opština"]=="NOVI SAD") & (df['Tip']=="SN SA JEDNIM VOZILOM")])
print(count_ukupan_broj_u_ns_sa_jednim_vozilom)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA SMRTNIM ISHODOM SA JEDNIM VOZILOM
print("Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom i jednim vozilom za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_jednim_vozilom_sa_poginulim = len(df[(df["Vrsta"]=="Sa poginulim") & (df['Tip']=='SN SA JEDNIM VOZILOM')])
print(count_ukupan_broj_u_srbiji_sa_jednim_vozilom_sa_poginulim)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA SMRTNIM ISHODOM SA JEDNIM VOZILOM
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom i jednim vozilom za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_jednim_vozilom_sa_poginulim = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa poginulim') & (df['Tip']=='SN SA JEDNIM VOZILOM')])
print(count_ukupan_broj_u_ns_sa_jednim_vozilom_sa_poginulim) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA POVREDAMA I JEDNIM VOZILOM
print("Ukupan broj saobracajnih nezgoda u Srbiji sa povredama i jednim vozilom za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_jednim_vozilom_sa_povredama = len(df[(df["Vrsta"]=="Sa povredjenim") & (df['Tip']=='SN SA JEDNIM VOZILOM')])
print(count_ukupan_broj_u_srbiji_sa_jednim_vozilom_sa_povredama)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA POVREDAMA I JEDNIM VOZILOM
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama i jednim vozilom za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_jednim_vozilom_sa_povredama = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa povredjenim') & (df['Tip']=='SN SA JEDNIM VOZILOM')])
print(count_ukupan_broj_u_ns_sa_jednim_vozilom_sa_povredama) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA MATERIJALNOM STETOM I JEDNIM VOZILOM
print("Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom i jednim vozilom za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_jednim_vozilom_sa_mat_stetom = len(df[(df["Vrsta"]=="Sa mat.stetom") & (df['Tip']=='SN SA JEDNIM VOZILOM')])
print(count_ukupan_broj_u_srbiji_sa_jednim_vozilom_sa_mat_stetom)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA MATERIJALNOM STETOM I JEDNIM VOZILOM
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom i jednim vozilom za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_jednim_vozilom_sa_mat_stetom = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa mat.stetom') & (df['Tip']=='SN SA JEDNIM VOZILOM')])
print(count_ukupan_broj_u_ns_sa_jednim_vozilom_sa_mat_stetom)

Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu sa jednim vozilom je:
3507
Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu sa jednim vozilom je:
161
Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom i jednim vozilom za 2022. godinu je:
64
Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom i jednim vozilom za 2022. godinu je:
0
Ukupan broj saobracajnih nezgoda u Srbiji sa povredama i jednim vozilom za 2022. godinu je:
1164
Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama i jednim vozilom za 2022. godinu je:
32
Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom i jednim vozilom za 2022. godinu je:
2279
Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom i jednim vozilom za 2022. godinu je:
129

In [9]:
#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA DVA ILI VISE VOZILA
print("Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu sa dva ili vise vozila je:")
count_ukupan_broj_u_srbiji_sa_dva_vozila = len(df[df['Tip'].str.contains("SN SA NAJMANjE DVA VOZILA")])
print(count_ukupan_broj_u_srbiji_sa_dva_vozila)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA DVA ILI VISE VOZILA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu sa dva ili vise vozila je:")
count_ukupan_broj_u_ns_sa_dva_vozila = len(df[(df["Opština"]=="NOVI SAD") & (df['Tip'].str.contains("SN SA NAJMANjE DVA VOZILA"))])
print(count_ukupan_broj_u_ns_sa_dva_vozila)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA SMRTNIM ISHODOM I DVA ILI VISE VOZILA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom i dva ili vise vozila za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_dva_vozila_sa_poginulim = len(df[(df["Vrsta"]=="Sa poginulim") & (df['Tip'].str.contains("SN SA NAJMANjE DVA VOZILA"))])
print(count_ukupan_broj_u_srbiji_sa_dva_vozila_sa_poginulim)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA SMRTNIM ISHODOM I DVA ILI VISE VOZILA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom i dva ili vise vozila za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_dva_vozila_sa_poginulim = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa poginulim') & (df['Tip'].str.contains("SN SA NAJMANjE DVA VOZILA"))])
print(count_ukupan_broj_u_ns_sa_dva_vozila_sa_poginulim) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA POVREDAMA I DVA ILI VISE VOZILA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa povredama i dva ili vise vozila za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_dva_vozila_sa_povredama = len(df[(df["Vrsta"]=="Sa povredjenim") & (df['Tip'].str.contains("SN SA NAJMANjE DVA VOZILA"))])
print(count_ukupan_broj_u_srbiji_sa_dva_vozila_sa_povredama)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA POVREDAMA I DVA ILI VISE VOZILA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama i dva ili vise vozila za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_dva_vozila_sa_povredama = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa povredjenim') & (df['Tip'].str.contains("SN SA NAJMANjE DVA VOZILA"))])
print(count_ukupan_broj_u_ns_sa_dva_vozila_sa_povredama) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA MATERIJALNOM STETOM I DVA ILI VISE VOZILA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom i dva ili vise vozila za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_dva_vozila_sa_mat_stetom = len(df[(df["Vrsta"]=="Sa mat.stetom") & (df['Tip'].str.contains("SN SA NAJMANjE DVA VOZILA"))])
print(count_ukupan_broj_u_srbiji_sa_dva_vozila_sa_mat_stetom)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA MATERIJALNOM STETOM I DVA ILI VISE VOZILA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom i dva ili vise vozila za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_dva_vozila_sa_mat_stetom = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa mat.stetom') & (df['Tip'].str.contains("SN SA NAJMANjE DVA VOZILA"))])
print(count_ukupan_broj_u_ns_sa_dva_vozila_sa_mat_stetom)

Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu sa dva ili vise vozila je:
8834
Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu sa dva ili vise vozila je:
673
Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom i dva ili vise vozila za 2022. godinu je:
87
Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom i dva ili vise vozila za 2022. godinu je:
3
Ukupan broj saobracajnih nezgoda u Srbiji sa povredama i dva ili vise vozila za 2022. godinu je:
3492
Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama i dva ili vise vozila za 2022. godinu je:
361
Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom i dva ili vise vozila za 2022. godinu je:
5255
Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom i dva ili vise vozila za 2022. godinu je:
309

In [10]:
#PRAVLJENJE ODGOVARAJUCEG FORMATA ZA DALJI RAD
df['Datum i vreme'] = df['Datum i vreme'].str.replace(',', '-', regex=True)
df['Datum i vreme'] = df['Datum i vreme'].str.replace('.', '', regex=True)
df['Datum i vreme'] = df['Datum i vreme'].str.replace(':', '', regex=True)

df['Datum i vreme'] = pd.to_datetime(df['Datum i vreme'], format='%d%m%Y-%H%M')

In [11]:
df

,ID,Policijska uprava,Opština,Datum i vreme,Geolokacija(X),Geolokacija(Y),Vrsta,Tip,Opis
0,1351594,BEOGRAD,BARAJEVO,2022-01-01 16:10:00,20.346290,44.603980,Sa povredjenim,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...
1,1351831,BEOGRAD,BARAJEVO,2022-01-01 02:30:00,20.430508,44.580407,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak ulevo sa k...
2,1351921,BEOGRAD,BARAJEVO,2022-01-06 11:00:00,20.398820,44.602510,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...
3,1352861,BEOGRAD,BARAJEVO,2022-01-06 12:10:00,20.414231,44.577657,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...
4,1351871,BEOGRAD,BARAJEVO,2022-01-08 20:15:00,20.344523,44.602351,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa leve strane kol...
...,...,...,...,...,...,...,...,...,...
15991,1377017,ŠABAC,ŠABAC,2022-06-28 10:50:00,19.737673,44.715512,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgode sa učešćem jednog vozila i životinja
15992,1377934,ŠABAC,ŠABAC,2022-06-29 21:00:00,19.741170,44.692048,Sa povredjenim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom bez prepreka na kolo...
15993,1377106,ŠABAC,ŠABAC,2022-06-29 00:20:00,19.687943,44.837582,Sa povredjenim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...
15994,1377341,ŠABAC,ŠABAC,2022-06-29 20:50:00,19.682128,44.745419,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Ostali sudari sa parkiranim vozilom
15995,1377477,ŠABAC,ŠABAC,2022-06-30 12:15:00,19.702106,44.749145,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...

In [12]:
#PRAVLJENJE KOLONE DAN U NEDELJI
df['Dan u nedelji'] = df['Datum i vreme'].dt.day_name()

In [13]:
df

,ID,Policijska uprava,Opština,Datum i vreme,Geolokacija(X),Geolokacija(Y),Vrsta,Tip,Opis,Dan u nedelji
0,1351594,BEOGRAD,BARAJEVO,2022-01-01 16:10:00,20.346290,44.603980,Sa povredjenim,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...,Saturday
1,1351831,BEOGRAD,BARAJEVO,2022-01-01 02:30:00,20.430508,44.580407,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak ulevo sa k...,Saturday
2,1351921,BEOGRAD,BARAJEVO,2022-01-06 11:00:00,20.398820,44.602510,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...,Thursday
3,1352861,BEOGRAD,BARAJEVO,2022-01-06 12:10:00,20.414231,44.577657,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...,Thursday
4,1351871,BEOGRAD,BARAJEVO,2022-01-08 20:15:00,20.344523,44.602351,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa leve strane kol...,Saturday
...,...,...,...,...,...,...,...,...,...,...
15991,1377017,ŠABAC,ŠABAC,2022-06-28 10:50:00,19.737673,44.715512,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgode sa učešćem jednog vozila i životinja,Tuesday
15992,1377934,ŠABAC,ŠABAC,2022-06-29 21:00:00,19.741170,44.692048,Sa povredjenim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom bez prepreka na kolo...,Wednesday
15993,1377106,ŠABAC,ŠABAC,2022-06-29 00:20:00,19.687943,44.837582,Sa povredjenim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...,Wednesday
15994,1377341,ŠABAC,ŠABAC,2022-06-29 20:50:00,19.682128,44.745419,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Ostali sudari sa parkiranim vozilom,Wednesday
15995,1377477,ŠABAC,ŠABAC,2022-06-30 12:15:00,19.702106,44.749145,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...,Thursday

In [14]:
#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI ZA VIKEND
print("Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu za vikend je:")
count_ukupan_broj_u_srbiji_vikend = len(df[(df["Dan u nedelji"]=="Saturday") | (df['Dan u nedelji']=="Sunday")])
print(count_ukupan_broj_u_srbiji_vikend)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU ZA VIKEND
print("Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu za vikend je:")
count_ukupan_broj_u_ns_vikend = len(df[(df["Opština"]=="NOVI SAD") & (df['Dan u nedelji']=="Saturday") | (df['Dan u nedelji']=="Sunday")])
print(count_ukupan_broj_u_ns_vikend)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA SMRTNIM ISHODOM ZA VIKEND
print("Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom za vikend za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_poginulim_vikend = len(df[(df["Vrsta"]=="Sa poginulim") & (df['Dan u nedelji']=="Saturday") | (df['Dan u nedelji']=="Sunday")])
print(count_ukupan_broj_u_srbiji_sa_poginulim_vikend)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA SMRTNIM ISHODOM ZA VIKEND
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom za vikend za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_poginulim_vikend = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa poginulim') & (df['Dan u nedelji']=="Saturday") | (df['Dan u nedelji']=="Sunday")])
print(count_ukupan_broj_u_ns_sa_poginulim_vikend) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA POVREDAMA ZA VIKEND
print("Ukupan broj saobracajnih nezgoda u Srbiji sa povredama za vikend za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_povredama_vikend = len(df[(df["Vrsta"]=="Sa povredjenim") & (df['Dan u nedelji']=="Saturday") | (df['Dan u nedelji']=="Sunday")])
print(count_ukupan_broj_u_srbiji_sa_povredama_vikend)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA POVREDAMA ZA VIKEND
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama za vikend za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_povredama_vikend = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa povredjenim') & (df['Dan u nedelji']=="Saturday") | (df['Dan u nedelji']=="Sunday")])
print(count_ukupan_broj_u_ns_sa_povredama_vikend) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA MATERIJALNOM STETOM ZA VIKEND
print("Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom za vikend za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_mat_stetom_vikend = len(df[(df["Vrsta"]=="Sa mat.stetom") & (df['Dan u nedelji']=="Saturday") | (df['Dan u nedelji']=="Sunday")])
print(count_ukupan_broj_u_srbiji_sa_mat_stetom_vikend)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA MATERIJALNOM STETOM ZA VIKEND
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom za vikend za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_mat_stetom_vikend = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa mat.stetom') & (df['Dan u nedelji']=="Saturday") | (df['Dan u nedelji']=="Sunday")])
print(count_ukupan_broj_u_ns_sa_mat_stetom_vikend)

Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu za vikend je:
4347
Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu za vikend je:
2130
Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom za vikend za 2022. godinu je:
2021
Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom za vikend za 2022. godinu je:
1980
Ukupan broj saobracajnih nezgoda u Srbiji sa povredama za vikend za 2022. godinu je:
2835
Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama za vikend za 2022. godinu je:
2037
Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom za vikend za 2022. godinu je:
3447
Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom za vikend za 2022. godinu je:
2069

In [15]:
#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI TOKOM RADNIH DANA
print("Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu tokom radnih dana je:")
count_ukupan_broj_u_srbiji_radni_dan = count_ukupan_broj_u_srbiji - count_ukupan_broj_u_srbiji_vikend 
print(count_ukupan_broj_u_srbiji_radni_dan)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU TOKOM RADNIH DANA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu tokom radnih dana je:")
count_ukupan_broj_u_ns_radni_dan = count_ukupan_broj_u_ns_vikend - count_ukupan_broj_u_ns
print(count_ukupan_broj_u_ns_radni_dan)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA SMRTNIM ISHODOM TOKOM RADNIH DANA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom tokom radnih dana za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_poginulim_radni_dan = count_ukupan_broj_u_srbiji_sa_poginulim_vikend - count_ukupan_broj_u_srbiji_sa_poginulim
print(count_ukupan_broj_u_srbiji_sa_poginulim_radni_dan)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA SMRTNIM ISHODOM TOKOM RADNIH DANA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom tokom radnih dana za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_poginulim_radni_dan = count_ukupan_broj_u_ns_sa_poginulim_vikend - count_ukupan_broj_u_ns_sa_poginulim
print(count_ukupan_broj_u_ns_sa_poginulim_radni_dan) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA POVREDAMA TOKOM RADNIH DANA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa povredama tokom radnih dana za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_povredama_radni_dan = count_ukupan_broj_u_srbiji_sa_povredama - count_ukupan_broj_u_srbiji_sa_povredama_vikend
print(count_ukupan_broj_u_srbiji_sa_povredama_radni_dan)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA POVREDAMA TOKOM RADNIH DANA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama tokom radnih dana za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_povredama_radni_dan = count_ukupan_broj_u_ns_sa_povredama_vikend - count_ukupan_broj_u_ns_sa_povredama
print(count_ukupan_broj_u_ns_sa_povredama_radni_dan) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA MATERIJALNOM STETOM TOKOM RADNIH DANA
print("Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom tokom radnih dana za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_mat_stetom_radni_dan = count_ukupan_broj_u_srbiji_sa_mat_stetom - count_ukupan_broj_u_srbiji_sa_mat_stetom_vikend
print(count_ukupan_broj_u_srbiji_sa_mat_stetom_radni_dan)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA MATERIJALNOM STETOM TOKOM RADNIH DANA
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom tokom radnih dana za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_mat_stetom_radni_dan = count_ukupan_broj_u_ns_sa_mat_stetom_vikend - count_ukupan_broj_u_ns_sa_mat_stetom
print(count_ukupan_broj_u_ns_sa_mat_stetom_radni_dan)

Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu tokom radnih dana je:
11649
Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu tokom radnih dana je:
1047
Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom tokom radnih dana za 2022. godinu je:
1803
Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom tokom radnih dana za 2022. godinu je:
1976
Ukupan broj saobracajnih nezgoda u Srbiji sa povredama tokom radnih dana za 2022. godinu je:
3083
Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama tokom radnih dana za 2022. godinu je:
1554
Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom tokom radnih dana za 2022. godinu je:
6413
Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom tokom radnih dana za 2022. godinu je:
1473

In [16]:
df['Vreme'] = pd.to_datetime(df['Datum i vreme'], format='%d%m%Y-%H%M').dt.time
df

,ID,Policijska uprava,Opština,Datum i vreme,Geolokacija(X),Geolokacija(Y),Vrsta,Tip,Opis,Dan u nedelji,Vreme
0,1351594,BEOGRAD,BARAJEVO,2022-01-01 16:10:00,20.346290,44.603980,Sa povredjenim,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...,Saturday,16:10:00
1,1351831,BEOGRAD,BARAJEVO,2022-01-01 02:30:00,20.430508,44.580407,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak ulevo sa k...,Saturday,02:30:00
2,1351921,BEOGRAD,BARAJEVO,2022-01-06 11:00:00,20.398820,44.602510,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...,Thursday,11:00:00
3,1352861,BEOGRAD,BARAJEVO,2022-01-06 12:10:00,20.414231,44.577657,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...,Thursday,12:10:00
4,1351871,BEOGRAD,BARAJEVO,2022-01-08 20:15:00,20.344523,44.602351,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa leve strane kol...,Saturday,20:15:00
...,...,...,...,...,...,...,...,...,...,...,...
15991,1377017,ŠABAC,ŠABAC,2022-06-28 10:50:00,19.737673,44.715512,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgode sa učešćem jednog vozila i životinja,Tuesday,10:50:00
15992,1377934,ŠABAC,ŠABAC,2022-06-29 21:00:00,19.741170,44.692048,Sa povredjenim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom bez prepreka na kolo...,Wednesday,21:00:00
15993,1377106,ŠABAC,ŠABAC,2022-06-29 00:20:00,19.687943,44.837582,Sa povredjenim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...,Wednesday,00:20:00
15994,1377341,ŠABAC,ŠABAC,2022-06-29 20:50:00,19.682128,44.745419,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Ostali sudari sa parkiranim vozilom,Wednesday,20:50:00
15995,1377477,ŠABAC,ŠABAC,2022-06-30 12:15:00,19.702106,44.749145,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa desne strane ko...,Thursday,12:15:00

In [17]:
pocetak_dana = datetime.time(5,0,1)
kraj_dana = datetime.time(22,0,0)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI PREKO DANA I PREKO NOCI
print("Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu preko dana je:")
count_ukupan_broj_u_srbiji_preko_dana = len(df[df["Vreme"].between(pocetak_dana, kraj_dana)])
print(count_ukupan_broj_u_srbiji_preko_dana)
print("Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu preko noci je:")
count_ukupan_broj_u_srbiji_preko_noci = count_ukupan_broj_u_srbiji - count_ukupan_broj_u_srbiji_preko_dana
print(count_ukupan_broj_u_srbiji_preko_noci)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU PREKO DANA I PREKO NOCI
print("Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu preko dana je:")
count_ukupan_broj_u_ns_preko_dana = len(df[(df["Opština"]=="NOVI SAD") & (df['Vreme'].between(pocetak_dana, kraj_dana))])
print(count_ukupan_broj_u_ns_preko_dana)
print("Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu preko noci je:")
count_ukupan_broj_u_ns_preko_noci = count_ukupan_broj_u_ns - count_ukupan_broj_u_ns_preko_dana
print(count_ukupan_broj_u_ns_preko_noci)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA SMRTNIM ISHODOM PREKO DANA I PREKO NOCI
print("Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom preko dana za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_poginulim_preko_dana = len(df[(df["Vrsta"]=="Sa poginulim") & (df['Vreme'].between(pocetak_dana, kraj_dana))])
print(count_ukupan_broj_u_srbiji_sa_poginulim_preko_dana)
print("Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom preko noci za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_poginulim_preko_noci = count_ukupan_broj_u_srbiji_sa_poginulim - count_ukupan_broj_u_srbiji_sa_poginulim_preko_dana
print(count_ukupan_broj_u_srbiji_sa_poginulim_preko_noci)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA SMRTNIM ISHODOM PREKO DANA I PREKO NOCI
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom preko dana za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_poginulim_preko_dana = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa poginulim') & (df['Vreme'].between(pocetak_dana, kraj_dana))])
print(count_ukupan_broj_u_ns_sa_poginulim_preko_dana) 
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom preko noci za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_poginulim_preko_noci = count_ukupan_broj_u_ns_sa_poginulim - count_ukupan_broj_u_ns_sa_poginulim_preko_dana
print(count_ukupan_broj_u_ns_sa_poginulim_preko_noci) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA POVREDAMA PREKO DANA I PREKO NOCI
print("Ukupan broj saobracajnih nezgoda u Srbiji sa povredama preko dana za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_povredama_preko_dana = len(df[(df["Vrsta"]=="Sa povredjenim") & (df['Vreme'].between(pocetak_dana, kraj_dana))])
print(count_ukupan_broj_u_srbiji_sa_povredama_preko_dana)
print("Ukupan broj saobracajnih nezgoda u Srbiji sa povredama preko noci za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_povredama_preko_noci = count_ukupan_broj_u_srbiji_sa_povredama - count_ukupan_broj_u_srbiji_sa_povredama_preko_dana
print(count_ukupan_broj_u_srbiji_sa_povredama_preko_noci)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA POVREDAMA PREKO DANA I PREKO NOCI
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama preko dana za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_povredama_preko_dana = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa povredjenim') & (df['Vreme'].between(pocetak_dana, kraj_dana))])
print(count_ukupan_broj_u_ns_sa_povredama_preko_dana) 
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama preko noci za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_povredama_preko_noci = count_ukupan_broj_u_ns_sa_povredama - count_ukupan_broj_u_ns_sa_povredama_preko_dana
print(count_ukupan_broj_u_ns_sa_povredama_preko_noci) 

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U SRBIJI SA MATERIJALNOM STETOM PREKO DANA I PREKO NOCI
print("Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom preko dana za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_mat_stetom_preko_dana = len(df[(df["Vrsta"]=="Sa mat.stetom") & (df['Vreme'].between(pocetak_dana, kraj_dana))])
print(count_ukupan_broj_u_srbiji_sa_mat_stetom_preko_dana)
print("Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom preko noci za 2022. godinu je:")
count_ukupan_broj_u_srbiji_sa_mat_stetom_preko_noci = count_ukupan_broj_u_srbiji_sa_mat_stetom - count_ukupan_broj_u_srbiji_sa_mat_stetom_preko_dana
print(count_ukupan_broj_u_srbiji_sa_mat_stetom_preko_noci)

#UKUPAN BROJ SAOBRACAJNIH NEZGODA U NOVOM SADU SA MATERIJALNOM STETOM PREKO DANA I PREKO NOCI
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom preko dana za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_mat_stetom_preko_dana = len(df[(df['Opština']=='NOVI SAD') & (df['Vrsta']=='Sa mat.stetom') & (df['Vreme'].between(pocetak_dana, kraj_dana))])
print(count_ukupan_broj_u_ns_sa_mat_stetom_preko_dana) 
print("Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom preko noci za 2022. godinu je:")
count_ukupan_broj_u_ns_sa_mat_stetom_preko_noci = count_ukupan_broj_u_ns_sa_mat_stetom - count_ukupan_broj_u_ns_sa_mat_stetom_preko_dana
print(count_ukupan_broj_u_ns_sa_mat_stetom_preko_noci)

Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu preko dana je:
13882
Ukupan broj saobracajnih nezgoda u Srbiji za 2022. godinu preko noci je:
2114
Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu preko dana je:
949
Ukupan broj saobracajnih nezgoda u Novom Sadu za 2022. godinu preko noci je:
134
Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom preko dana za 2022. godinu je:
179
Ukupan broj saobracajnih nezgoda u Srbiji sa smrtnim ishodom preko noci za 2022. godinu je:
39
Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom preko dana za 2022. godinu je:
4
Ukupan broj saobracajnih nezgoda u Novom Sadu sa smrtnim ishodom preko noci za 2022. godinu je:
0
Ukupan broj saobracajnih nezgoda u Srbiji sa povredama preko dana za 2022. godinu je:
5283
Ukupan broj saobracajnih nezgoda u Srbiji sa povredama preko noci za 2022. godinu je:
635
Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama preko dana za 2022. godinu je:
439
Ukupan broj saobracajnih nezgoda u Novom Sadu sa povredama preko noci za 2022. godinu je:
44
Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom preko dana za 2022. godinu je:
8420
Ukupan broj saobracajnih nezgoda u Srbiji sa materijalnom stetom preko noci za 2022. godinu je:
1440
Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom preko dana za 2022. godinu je:
506
Ukupan broj saobracajnih nezgoda u Novom Sadu sa materijalnom stetom preko noci za 2022. godinu je:
90

In [18]:
d = {
    "Ukupan broj u SRB": count_ukupan_broj_u_srbiji,
    "Ukupan broj u SRB sa poginulim": count_ukupan_broj_u_srbiji_sa_poginulim,
    "Ukupan broj u SRB sa povredama": count_ukupan_broj_u_srbiji_sa_povredama,
    "Ukupan broj u SRB sa mat. stetom": count_ukupan_broj_u_srbiji_sa_mat_stetom,
    "Ukupan broj u NS": count_ukupan_broj_u_ns,
    "Ukupan broj u NS sa poginulim": count_ukupan_broj_u_ns_sa_poginulim,
    "Ukupan broj u NS sa povredama": count_ukupan_broj_u_ns_sa_povredama,
    "Ukupan broj u NS sa mat. stetom": count_ukupan_broj_u_ns_sa_mat_stetom,
}
df = pd.DataFrame(d, index=[0])
df

,Ukupan broj u SRB,Ukupan broj u SRB sa poginulim,Ukupan broj u SRB sa povredama,Ukupan broj u SRB sa mat. stetom,Ukupan broj u NS,Ukupan broj u NS sa poginulim,Ukupan broj u NS sa povredama,Ukupan broj u NS sa mat. stetom
0,15996,218,5918,9860,1083,4,483,596

In [19]:
d = {
    "Ukupan broj u SRB sa pesacima": count_ukupan_broj_u_srbiji_sa_pesacima,
    "Ukupan broj u SRB sa poginulim sa pesacima": count_ukupan_broj_u_srbiji_sa_pesacima_sa_poginulim,
    "Ukupan broj u SRB sa povredama sa pesacima": count_ukupan_broj_u_srbiji_sa_pesacima_sa_povredama,
    "Ukupan broj u SRB sa mat. stetom sa pesacima": count_ukupan_broj_u_srbiji_sa_pesacima_sa_mat_stetom,
    "Ukupan broj u NS sa pesacima": count_ukupan_broj_u_ns_sa_pesacima,
    "Ukupan broj u NS sa poginulim sa pesacima": count_ukupan_broj_u_ns_sa_pesacima_sa_poginulim,
    "Ukupan broj u NS sa povredama sa pesacima": count_ukupan_broj_u_ns_sa_pesacima_sa_povredama,
    "Ukupan broj u NS sa mat. stetom sa pesacima": count_ukupan_broj_u_ns_sa_pesacima_sa_mat_stetom,
}
df = pd.DataFrame(d, index=[0])
df

,Ukupan broj u SRB sa pesacima,Ukupan broj u SRB sa poginulim sa pesacima,Ukupan broj u SRB sa povredama sa pesacima,Ukupan broj u SRB sa mat. stetom sa pesacima,Ukupan broj u NS sa pesacima,Ukupan broj u NS sa poginulim sa pesacima,Ukupan broj u NS sa povredama sa pesacima,Ukupan broj u NS sa mat. stetom sa pesacima
0,1168,58,1092,18,83,1,79,3

In [20]:
d = {
    "Ukupan broj u SRB sa parkiranim vozilom": count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom,
    "Ukupan broj u SRB sa poginulim sa parkiranim vozilom": count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom_sa_poginulim,
    "Ukupan broj u SRB sa povredama sa parkiranim vozilom": count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom_sa_povredama,
    "Ukupan broj u SRB sa mat. stetom sa parkiranim vozilom": count_ukupan_broj_u_srbiji_sa_parkiranim_vozilom_sa_mat_stetom,
    "Ukupan broj u NS sa parkiranim vozilom": count_ukupan_broj_u_ns_sa_parkiranim_vozilom,
    "Ukupan broj u NS sa poginulim sa parkiranim vozilom": count_ukupan_broj_u_ns_sa_parkiranim_vozilom_sa_poginulim,
    "Ukupan broj u NS sa povredama sa parkiranim vozilom": count_ukupan_broj_u_ns_sa_parkiranim_vozilom_sa_povredama,
    "Ukupan broj u NS sa mat. stetom sa parkiranim vozilom": count_ukupan_broj_u_ns_sa_parkiranim_vozilom_sa_mat_stetom,
}
df = pd.DataFrame(d, index=[0])
df

,Ukupan broj u SRB sa parkiranim vozilom,Ukupan broj u SRB sa poginulim sa parkiranim vozilom,Ukupan broj u SRB sa povredama sa parkiranim vozilom,Ukupan broj u SRB sa mat. stetom sa parkiranim vozilom,Ukupan broj u NS sa parkiranim vozilom,Ukupan broj u NS sa poginulim sa parkiranim vozilom,Ukupan broj u NS sa povredama sa parkiranim vozilom,Ukupan broj u NS sa mat. stetom sa parkiranim vozilom
0,2487,9,170,2308,166,0,11,155

In [21]:
d = {
    "Ukupan broj u SRB sa jednim vozilom": count_ukupan_broj_u_srbiji_sa_jednim_vozilom,
    "Ukupan broj u SRB sa poginulim sa jednim vozilom": count_ukupan_broj_u_srbiji_sa_jednim_vozilom_sa_poginulim,
    "Ukupan broj u SRB sa povredama sa jednim vozilom": count_ukupan_broj_u_srbiji_sa_jednim_vozilom_sa_povredama,
    "Ukupan broj u SRB sa mat. stetom sa jednim vozilom": count_ukupan_broj_u_srbiji_sa_jednim_vozilom_sa_mat_stetom,
    "Ukupan broj u NS sa jednim vozilom": count_ukupan_broj_u_ns_sa_jednim_vozilom,
    "Ukupan broj u NS sa poginulim sa jednim vozilom": count_ukupan_broj_u_ns_sa_jednim_vozilom_sa_poginulim,
    "Ukupan broj u NS sa povredama sa jednim vozilom": count_ukupan_broj_u_ns_sa_jednim_vozilom_sa_povredama,
    "Ukupan broj u NS sa mat. stetom sa jednim vozilom": count_ukupan_broj_u_ns_sa_jednim_vozilom_sa_mat_stetom,
}
df = pd.DataFrame(d, index=[0])
df

,Ukupan broj u SRB sa jednim vozilom,Ukupan broj u SRB sa poginulim sa jednim vozilom,Ukupan broj u SRB sa povredama sa jednim vozilom,Ukupan broj u SRB sa mat. stetom sa jednim vozilom,Ukupan broj u NS sa jednim vozilom,Ukupan broj u NS sa poginulim sa jednim vozilom,Ukupan broj u NS sa povredama sa jednim vozilom,Ukupan broj u NS sa mat. stetom sa jednim vozilom
0,3507,64,1164,2279,161,0,32,129

In [22]:
d = {
    "Ukupan broj u SRB sa dva vozila": count_ukupan_broj_u_srbiji_sa_dva_vozila,
    "Ukupan broj u SRB sa poginulim sa dva vozila": count_ukupan_broj_u_srbiji_sa_dva_vozila_sa_poginulim,
    "Ukupan broj u SRB sa povredama sa dva vozila": count_ukupan_broj_u_srbiji_sa_dva_vozila_sa_povredama,
    "Ukupan broj u SRB sa mat. stetom sa dva vozila": count_ukupan_broj_u_srbiji_sa_dva_vozila_sa_mat_stetom,
    "Ukupan broj u NS sa dva vozila": count_ukupan_broj_u_ns_sa_dva_vozila,
    "Ukupan broj u NS sa poginulim sa dva vozila": count_ukupan_broj_u_ns_sa_dva_vozila_sa_poginulim,
    "Ukupan broj u NS sa povredama sa dva vozila": count_ukupan_broj_u_ns_sa_dva_vozila_sa_povredama,
    "Ukupan broj u NS sa mat. stetom sa dva vozila": count_ukupan_broj_u_ns_sa_dva_vozila_sa_mat_stetom,
}
df = pd.DataFrame(d, index=[0])
df

,Ukupan broj u SRB sa dva vozila,Ukupan broj u SRB sa poginulim sa dva vozila,Ukupan broj u SRB sa povredama sa dva vozila,Ukupan broj u SRB sa mat. stetom sa dva vozila,Ukupan broj u NS sa dva vozila,Ukupan broj u NS sa poginulim sa dva vozila,Ukupan broj u NS sa povredama sa dva vozila,Ukupan broj u NS sa mat. stetom sa dva vozila
0,8834,87,3492,5255,673,3,361,309

In [23]:
d = {
    "Ukupan broj u SRB za vikend": count_ukupan_broj_u_srbiji_vikend,
    "Ukupan broj u SRB sa poginulim za vikend": count_ukupan_broj_u_srbiji_sa_poginulim_vikend,
    "Ukupan broj u SRB sa povredama za vikend": count_ukupan_broj_u_srbiji_sa_povredama_vikend,
    "Ukupan broj u SRB sa mat. stetom za vikend": count_ukupan_broj_u_srbiji_sa_mat_stetom_vikend,
    "Ukupan broj u NS za vikend": count_ukupan_broj_u_ns_vikend,
    "Ukupan broj u NS sa poginulim za vikend": count_ukupan_broj_u_ns_sa_poginulim_vikend,
    "Ukupan broj u NS sa povredama za vikend": count_ukupan_broj_u_ns_sa_povredama_vikend,
    "Ukupan broj u NS sa mat. stetom za vikend": count_ukupan_broj_u_ns_sa_mat_stetom_vikend,
}
df = pd.DataFrame(d, index=[0])
df

,Ukupan broj u SRB za vikend,Ukupan broj u SRB sa poginulim za vikend,Ukupan broj u SRB sa povredama za vikend,Ukupan broj u SRB sa mat. stetom za vikend,Ukupan broj u NS za vikend,Ukupan broj u NS sa poginulim za vikend,Ukupan broj u NS sa povredama za vikend,Ukupan broj u NS sa mat. stetom za vikend
0,4347,2021,2835,3447,2130,1980,2037,2069

In [24]:
d = {
    "Ukupan broj u SRB tokom radnih dana": count_ukupan_broj_u_srbiji_radni_dan,
    "Ukupan broj u SRB sa poginulim tokom radnih dana": count_ukupan_broj_u_srbiji_sa_poginulim_radni_dan,
    "Ukupan broj u SRB sa povredama tokom radnih dana": count_ukupan_broj_u_srbiji_sa_povredama_radni_dan,
    "Ukupan broj u SRB sa mat. stetom tokom radnih dana": count_ukupan_broj_u_srbiji_sa_mat_stetom_radni_dan,
    "Ukupan broj u NS tokom radnih dana": count_ukupan_broj_u_ns_radni_dan,
    "Ukupan broj u NS sa poginulim tokom radnih dana": count_ukupan_broj_u_ns_sa_poginulim_radni_dan,
    "Ukupan broj u NS sa povredama tokom radnih dana": count_ukupan_broj_u_ns_sa_povredama_radni_dan,
    "Ukupan broj u NS sa mat. stetom tokom radnih dana": count_ukupan_broj_u_ns_sa_mat_stetom_radni_dan,
}
df = pd.DataFrame(d, index=[0])
df

,Ukupan broj u SRB tokom radnih dana,Ukupan broj u SRB sa poginulim tokom radnih dana,Ukupan broj u SRB sa povredama tokom radnih dana,Ukupan broj u SRB sa mat. stetom tokom radnih dana,Ukupan broj u NS tokom radnih dana,Ukupan broj u NS sa poginulim tokom radnih dana,Ukupan broj u NS sa povredama tokom radnih dana,Ukupan broj u NS sa mat. stetom tokom radnih dana
0,11649,1803,3083,6413,1047,1976,1554,1473

In [25]:
d = {
    "Ukupan broj u SRB preko dana": count_ukupan_broj_u_srbiji_preko_dana,
    "Ukupan broj u SRB sa poginulim preko dana": count_ukupan_broj_u_srbiji_sa_poginulim_preko_dana,
    "Ukupan broj u SRB sa povredama preko dana": count_ukupan_broj_u_srbiji_sa_povredama_preko_dana,
    "Ukupan broj u SRB sa mat. stetom preko dana": count_ukupan_broj_u_srbiji_sa_mat_stetom_preko_dana,
    "Ukupan broj u NS preko dana": count_ukupan_broj_u_ns_preko_dana,
    "Ukupan broj u NS sa poginulim preko dana": count_ukupan_broj_u_ns_sa_poginulim_preko_dana,
    "Ukupan broj u NS sa povredama preko dana": count_ukupan_broj_u_ns_sa_povredama_preko_dana,
    "Ukupan broj u NS sa mat. stetom preko dana": count_ukupan_broj_u_ns_sa_mat_stetom_preko_dana,
}
df = pd.DataFrame(d, index=[0])
df

,Ukupan broj u SRB preko dana,Ukupan broj u SRB sa poginulim preko dana,Ukupan broj u SRB sa povredama preko dana,Ukupan broj u SRB sa mat. stetom preko dana,Ukupan broj u NS preko dana,Ukupan broj u NS sa poginulim preko dana,Ukupan broj u NS sa povredama preko dana,Ukupan broj u NS sa mat. stetom preko dana
0,13882,179,5283,8420,949,4,439,506

In [26]:
d = {
    "Ukupan broj u SRB preko noci": count_ukupan_broj_u_srbiji_preko_noci,
    "Ukupan broj u SRB sa poginulim preko noci": count_ukupan_broj_u_srbiji_sa_poginulim_preko_noci,
    "Ukupan broj u SRB sa povredama preko noci": count_ukupan_broj_u_srbiji_sa_povredama_preko_noci,
    "Ukupan broj u SRB sa mat. stetom preko noci": count_ukupan_broj_u_srbiji_sa_mat_stetom_preko_noci,
    "Ukupan broj u NS preko noci": count_ukupan_broj_u_ns_preko_noci,
    "Ukupan broj u NS sa poginulim preko noci": count_ukupan_broj_u_ns_sa_poginulim_preko_noci,
    "Ukupan broj u NS sa povredama preko noci": count_ukupan_broj_u_ns_sa_povredama_preko_noci,
    "Ukupan broj u NS sa mat. stetom preko noci": count_ukupan_broj_u_ns_sa_mat_stetom_preko_noci,
}
df = pd.DataFrame(d, index=[0])
df

,Ukupan broj u SRB preko noci,Ukupan broj u SRB sa poginulim preko noci,Ukupan broj u SRB sa povredama preko noci,Ukupan broj u SRB sa mat. stetom preko noci,Ukupan broj u NS preko noci,Ukupan broj u NS sa poginulim preko noci,Ukupan broj u NS sa povredama preko noci,Ukupan broj u NS sa mat. stetom preko noci
0,2114,39,635,1440,134,0,44,90